site_name: 我的文档
nav:
    - 目录: 'index.md'
    - '数学': 
        - '高等数学': 'math.md'
        - '线性代数': 'math.md'
        - '概率统计': 'math.md'
    - 关于: 'about.md'
# theme : readthedocs
theme_dir: 'theme'
title: My Document
summary: A brief description of my document.
authors:
    - Author001
    - Author002
date: 2018-07-10
some_url: https://example.com
use_directory_urls: true
dev_addr: 0.0.0.0:8859